services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: servicedb
      POSTGRES_USER: serviceuser
      POSTGRES_PASSWORD: servicepass
    ports:
      - "15432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  api:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: servicedb
      DB_USER: serviceuser
      DB_PASSWORD: servicepass
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./app:/app/app
    command: ["uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]

  api3:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: servicedb
      DB_USER: serviceuser
      DB_PASSWORD: servicepass
    ports:
      - "8001:8000"
    depends_on:
      - db
    volumes:
      - ./appJobs:/app/app
    command: ["uvicorn", "app.main3:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]


  

volumes:
  db_data:


